# Numpy  آشنایی و کار با کتابخانه  

In [70]:
import numpy as np
np.random.seed(0) # seed -> تولید مجدد دیتا
x1 = np.random.randint(10, size=6) # یک بعدی array
x2 = np.random.randint(10, size=(3, 4)) # دو بعدی array
x3 = np.random.randint(10, size=(3, 4, 5)) # سه بعدی array

In [71]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [72]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [73]:
print("dtype:", x3.dtype)

dtype: int32


In [74]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [75]:
x1

array([5, 0, 3, 3, 7, 9])

In [76]:
x1[0]

5

In [77]:
x1[-2]

7

In [78]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [79]:
x2[0, 0]

3

In [80]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [81]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

In [ ]:
# subarray دسترسی به

In [ ]:
# یک بعدی

In [82]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x[:5]

array([0, 1, 2, 3, 4])

In [85]:
x[5:]

array([5, 6, 7, 8, 9])

In [88]:
x[4:7]

array([4, 5, 6])

In [89]:
x[::2]

array([0, 2, 4, 6, 8])

In [90]:
x[1::2]

array([1, 3, 5, 7, 9])

In [91]:
x[::-1]# تمام مقادیر برعکس می شوند

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# چند بعدی

In [92]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [93]:
x2[:2, :3]# دو سطر، سه ستون

array([[12,  5,  2],
       [ 7,  6,  8]])

In [94]:
x2[:3, ::2]# تمامی سطرها، ستون ها یکی در میان

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [95]:
x2[::-1, ::-1] #  همه با هم برعکس

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [96]:
print(x2[:, 0]) # اولین ستون x2

[12  7  1]


In [97]:
print(x2[0]) #  x2[0, :]  برابر با

[12  5  2  4]


In [ ]:
# Reshaping of Arrays

In [98]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
x = np.array([1, 2, 3])
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
#Array Concatenation and Splitting

In [ ]:
#1.Concatenation of arrays

In [100]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [101]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [103]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [104]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [105]:
y = np.array([[99],
              [99]])

In [106]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
#Splitting of arrays

In [109]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1]


In [110]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [112]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Numpy استفاده از عملگرها در   
Operator                       ufunc Description
+ np.add                        (e.g., 1 + 1 = 2)
- np.subtract                   (e.g., 3 - 2 = 1)
- np.negative                      (e.g., -2)
* np.multiply                   (e.g., 2 * 3 = 6)
/ np.divide                     (e.g., 3 / 2 = 1.5)
// np.floor_divide              (e.g., 3 // 2 = 1)
** np.power                     (e.g., 2 ** 3 = 8)
% np.mod                        (e.g., 9 % 4 = 1)

In [115]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print(-(0.5*x + 1) ** 2)
np.add(x, 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[-1.   -2.25 -4.   -6.25]


array([2, 3, 4, 5])

In [116]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [117]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

In [119]:
shahin= np.random.random(100)
shahin

array([1.66847513e-01, 7.79051020e-01, 8.64933296e-01, 4.11396724e-01,
       1.39972585e-01, 3.32223853e-02, 9.82574960e-01, 3.73290751e-01,
       4.20075370e-01, 5.05881151e-02, 3.65496106e-01, 1.66279737e-02,
       2.30742335e-01, 7.64911699e-01, 9.44123519e-01, 7.49999249e-01,
       3.39403819e-01, 4.89548937e-01, 3.38985117e-01, 1.79490261e-01,
       1.70986599e-01, 4.63450977e-01, 8.74572958e-01, 9.44119751e-01,
       6.08252866e-01, 5.96655406e-01, 7.83644245e-01, 5.00026298e-01,
       5.03700568e-02, 6.99098075e-01, 9.92396399e-01, 2.67262538e-01,
       6.79090616e-01, 8.64281443e-01, 7.50844246e-01, 9.64489768e-01,
       5.54242435e-01, 2.12390499e-01, 2.22443224e-01, 2.18749374e-01,
       5.69573535e-01, 4.52109035e-01, 9.70236683e-01, 6.80544691e-01,
       8.52955659e-02, 5.64183327e-02, 4.87837704e-01, 8.81004562e-01,
       9.76404387e-01, 6.17657916e-01, 5.42498775e-01, 8.54613580e-01,
       7.43834545e-01, 4.78596326e-01, 6.77081574e-01, 6.07045061e-01,
      

In [120]:
np.min(shahin), np.max(shahin)

(5.535686500857118e-05, 0.9923963988886326)

In [ ]:
# نمونه Aggregation

In [121]:
M = np.random.random((3, 4))
print(M)

[[0.09259617 0.21745049 0.74925442 0.73169376]
 [0.04561464 0.20915703 0.28691504 0.67726331]
 [0.06303829 0.55564924 0.00924007 0.8330381 ]]


In [122]:
M.sum()

4.470910550058228

In [123]:
M.min(axis=0)

array([0.04561464, 0.20915703, 0.00924007, 0.67726331])

In [124]:
M.max(axis=1)

array([0.74925442, 0.67726331, 0.8330381 ])

In [ ]:
# Sorting Arrays

In [125]:
import numpy as np
def selection_sort(x):
    for i in range(len(x)):      
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x


x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [126]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [127]:
print(np.sort(x))

[1 2 3 4 5]


In [128]:
X = np.random.randint(0, 10, (4, 6))
X

array([[7, 0, 8, 6, 8, 9],
       [8, 3, 6, 1, 7, 4],
       [9, 2, 0, 8, 2, 7],
       [8, 4, 4, 1, 7, 6]])

In [129]:
# sort each column of X
np.sort(X, axis=0)

array([[7, 0, 0, 1, 2, 4],
       [8, 2, 4, 1, 7, 6],
       [8, 3, 6, 6, 7, 7],
       [9, 4, 8, 8, 8, 9]])

In [130]:
# sort each row of X
np.sort(X, axis=1)

array([[0, 6, 7, 8, 8, 9],
       [1, 3, 4, 6, 7, 8],
       [0, 2, 2, 7, 8, 9],
       [1, 4, 4, 6, 7, 8]])